/**
 * Do not edit directly, this file was auto-generated.
 */

export default tokens;

declare interface DesignToken {
  value?: any;
  type?: string;
  comment?: string;
  name?: string;
  themeable?: boolean;
  attributes?: Record<string, unknown>;
  [key: string]: any;
}

declare const tokens: {
  primitive: {
    color: {
      cyan: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      blue: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      pink: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      orange: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      yellow: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      green: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      red: {
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
      };
      white: {
        '0': DesignToken;
        '5': DesignToken;
        '7': DesignToken;
        '10': DesignToken;
        '20': DesignToken;
        '30': DesignToken;
        '50': DesignToken;
        '70': DesignToken;
        '100': DesignToken;
      };
      black: {
        '0': DesignToken;
        '5': DesignToken;
        '7': DesignToken;
        '10': DesignToken;
        '20': DesignToken;
        '30': DesignToken;
        '50': DesignToken;
        '70': DesignToken;
        '100': DesignToken;
      };
      grey: {
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
        transparent: {
          '1-70': DesignToken;
        };
      };
      purple: {
        solid: {
          '1': DesignToken;
          '2': DesignToken;
          '3': DesignToken;
          '4': DesignToken;
          '5': DesignToken;
          '6': DesignToken;
          '7': DesignToken;
          '8': DesignToken;
          '9': DesignToken;
          '10': DesignToken;
        };
        transparent: {
          '8 - 30': DesignToken;
          '8 - 20': DesignToken;
          '8 - 10': DesignToken;
          '8 - 0': DesignToken;
        };
      };
    };
  };
  color: {
    background: {
      main: DesignToken;
      'grey-lvl-1': DesignToken;
      'grey-lvl-2': DesignToken;
      'white-light': DesignToken;
      'black-strong': DesignToken;
      'black-medium': DesignToken;
      'white-extra-light': DesignToken;
      'main-strong': DesignToken;
      purple: DesignToken;
      'purple-light': DesignToken;
      white: DesignToken;
      'white-medium-strong': DesignToken;
      'green-light': DesignToken;
      green: DesignToken;
      'red-light': DesignToken;
      red: DesignToken;
      'orange-light': DesignToken;
      orange: DesignToken;
      'white-medium-light': DesignToken;
    };
    'interactive-surface': {
      solid: {
        'grey-lvl-1': {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
          enabled: DesignToken;
        };
        'grey-lvl-2': {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
          enabled: DesignToken;
        };
        purple: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        red: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        white: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        yellow: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        green: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        orange: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
      };
      transparent: {
        purple: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        red: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        white: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        orange: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        green: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        black: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
        yellow: {
          enabled: DesignToken;
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          disabled: DesignToken;
        };
      };
      ghost: {
        purple: {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          enabled: DesignToken;
          disabled: DesignToken;
        };
        red: {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          enabled: DesignToken;
          disabled: DesignToken;
        };
        white: {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          enabled: DesignToken;
          disabled: DesignToken;
        };
        green: {
          hover: DesignToken;
          active: DesignToken;
          selected: DesignToken;
          enabled: DesignToken;
          disabled: DesignToken;
        };
      };
    };
    text: {
      primary: DesignToken;
      secondary: DesignToken;
      tertiary: DesignToken;
      disabled: DesignToken;
      purple: DesignToken;
      green: DesignToken;
      red: DesignToken;
      orange: DesignToken;
      yellow: DesignToken;
      inverted: DesignToken;
      'purple-inverted': DesignToken;
      'inverted-strong': DesignToken;
    };
    border: {
      'white-light': DesignToken;
      'white-medium-strong': DesignToken;
      purple: DesignToken;
      'white-medium': DesignToken;
      grey: DesignToken;
      black: DesignToken;
      white: DesignToken;
      red: DesignToken;
      green: DesignToken;
      orange: DesignToken;
      yellow: DesignToken;
    };
    link: {
      enabled: DesignToken;
      hover: DesignToken;
      active: DesignToken;
    };
  };
  typography: {
    font: {
      family: {
        'headline-s': DesignToken;
        'body-m': DesignToken;
        'caption-l': DesignToken;
        'brand-caption-l': DesignToken;
        'caption-mono': DesignToken;
        'body-l': DesignToken;
        'headline-m': DesignToken;
        'headline-l': DesignToken;
        'headline-xl': DesignToken;
        'headline-2xl': DesignToken;
        'headline-3xl': DesignToken;
        'brand-body-m': DesignToken;
        'brand-body-l': DesignToken;
        'brand-headline-s': DesignToken;
        'brand-headline-m': DesignToken;
        'brand-headline-l': DesignToken;
        'brand-headline-xl': DesignToken;
        'brand-headline-2xl': DesignToken;
        'brand-headline-3xl': DesignToken;
      };
      'line-height': {
        'headline-s': DesignToken;
        'caption-l': DesignToken;
        'body-m': DesignToken;
        'body-l': DesignToken;
        'headline-m': DesignToken;
        'headline-xl': DesignToken;
        'headline-l': DesignToken;
        'headline-2xl': DesignToken;
        'headline-3xl': DesignToken;
        'caption-mono': DesignToken;
        'brand-caption-l': DesignToken;
        'brand-body-m': DesignToken;
        'brand-body-l': DesignToken;
        'brand-headline-s': DesignToken;
        'brand-headline-m': DesignToken;
        'brand-headline-l': DesignToken;
        'brand-headline-xl': DesignToken;
        'brand-headline-2xl': DesignToken;
        'brand-headline-3xl': DesignToken;
      };
      size: {
        'body-l': DesignToken;
        'caption-l': DesignToken;
        'body-m': DesignToken;
        'headline-s': DesignToken;
        'headline-m': DesignToken;
        'headline-l': DesignToken;
        'headline-xl': DesignToken;
        'headline-2xl': DesignToken;
        'headline-3xl': DesignToken;
        'caption-mono': DesignToken;
        'brand-caption-l': DesignToken;
        'brand-body-m': DesignToken;
        'brand-body-l': DesignToken;
        'brand-headline-s': DesignToken;
        'brand-headline-m': DesignToken;
        'brand-headline-l': DesignToken;
        'brand-headline-xl': DesignToken;
        'brand-headline-2xl': DesignToken;
        'brand-headline-3xl': DesignToken;
      };
      'letter-spacing': {
        'caption-l': DesignToken;
        'body-m': DesignToken;
        'body-l': DesignToken;
        'headline-s': DesignToken;
        'headline-m': DesignToken;
        'headline-l': DesignToken;
        'headline-xl': DesignToken;
        'headline-2xl': DesignToken;
        'headline-3xl': DesignToken;
        'caption-mono': DesignToken;
        'brand-headline-3xl': DesignToken;
        'brand-headline-2xl': DesignToken;
        'brand-headline-xl': DesignToken;
        'brand-headline-l': DesignToken;
        'brand-headline-m': DesignToken;
        'brand-caption-l': DesignToken;
        'brand-body-m': DesignToken;
        'brand-body-l': DesignToken;
        'brand-headline-s': DesignToken;
      };
      weight: {
        extrablack: DesignToken;
        regular: DesignToken;
        extrabold: DesignToken;
        medium: DesignToken;
      };
    };
  };
  spacing: {
    spacing: {
      '1': DesignToken;
      '2': DesignToken;
      '3': DesignToken;
      '4': DesignToken;
      '8': DesignToken;
      '12': DesignToken;
      '16': DesignToken;
      '32': DesignToken;
    };
  };
  radius: {
    radius: {
      '1': DesignToken;
      '2': DesignToken;
      '3': DesignToken;
      '4': DesignToken;
      '6': DesignToken;
      '8': DesignToken;
      '16': DesignToken;
      full: DesignToken;
    };
  };
  iconography: {
    font: {
      family: {
        icon: DesignToken;
      };
      weight: {
        medium: DesignToken;
        bold: DesignToken;
      };
      size: {
        '4': DesignToken;
        '5': DesignToken;
        '6': DesignToken;
        '7': DesignToken;
        '8': DesignToken;
        '10': DesignToken;
        '12': DesignToken;
        '16': DesignToken;
        '24': DesignToken;
        '32': DesignToken;
      };
      'line-height': {
        '4': DesignToken;
        '5': DesignToken;
        '6': DesignToken;
        '7': DesignToken;
        '8': DesignToken;
        '10': DesignToken;
        '12': DesignToken;
        '16': DesignToken;
        '24': DesignToken;
        '32': DesignToken;
      };
    };
  };
  breakpoint: {
    xs: DesignToken;
    sm: DesignToken;
    md: DesignToken;
    lg: DesignToken;
    xl: DesignToken;
  };
  content: {
    'icon-glyph': {
      placeholder: DesignToken;
      activity: DesignToken;
      arrow_trending_down: DesignToken;
      arrow_trending_up: DesignToken;
      bar_chart_peak: DesignToken;
      bar_chart_rise: DesignToken;
      circular_chart: DesignToken;
      credit_card: DesignToken;
      paypal: DesignToken;
      shopping_bag: DesignToken;
      shopping_cart: DesignToken;
      shopping_cart_add: DesignToken;
      shopping_cart_dashed: DesignToken;
      store: DesignToken;
      visa: DesignToken;
      wallet: DesignToken;
      compass: DesignToken;
      globe: DesignToken;
      globe_lock: DesignToken;
      globe_minus: DesignToken;
      globe_plus: DesignToken;
      globe_dashed: DesignToken;
      map: DesignToken;
      map_pin: DesignToken;
      navigation: DesignToken;
      path: DesignToken;
      cloud: DesignToken;
      cloud_drizzle: DesignToken;
      cloud_lightning: DesignToken;
      cloud_dashed: DesignToken;
      cloud_rain: DesignToken;
      cloud_snow: DesignToken;
      drop: DesignToken;
      flame: DesignToken;
      ice: DesignToken;
      moon: DesignToken;
      sun: DesignToken;
      sunrise: DesignToken;
      sunset: DesignToken;
      thermometer: DesignToken;
      wind: DesignToken;
      zap: DesignToken;
      apple: DesignToken;
      chrome: DesignToken;
      crossplatform: DesignToken;
      linux: DesignToken;
      windows: DesignToken;
      xbox: DesignToken;
      discord: DesignToken;
      facebook: DesignToken;
      linkedin: DesignToken;
      medium: DesignToken;
      telegram: DesignToken;
      twitter: DesignToken;
      youtube: DesignToken;
      at_sign: DesignToken;
      beta: DesignToken;
      blockchain: DesignToken;
      bluetooth: DesignToken;
      branch: DesignToken;
      camera: DesignToken;
      camera_dashed: DesignToken;
      cloud_download: DesignToken;
      cloud_upload: DesignToken;
      code_brackets: DesignToken;
      coins_pile: DesignToken;
      collectible: DesignToken;
      compatible: DesignToken;
      computer: DesignToken;
      crypto: DesignToken;
      crypto_add: DesignToken;
      crypto_exchanged: DesignToken;
      crypto_received: DesignToken;
      crypto_sent: DesignToken;
      demo: DesignToken;
      dlc: DesignToken;
      exception: DesignToken;
      headphones: DesignToken;
      mail: DesignToken;
      merge: DesignToken;
      message: DesignToken;
      message_chat: DesignToken;
      mic: DesignToken;
      mic_dashed: DesignToken;
      monitor_zap: DesignToken;
      network: DesignToken;
      phone: DesignToken;
      phone_call: DesignToken;
      phone_forwarded: DesignToken;
      phone_incoming: DesignToken;
      phone_missed: DesignToken;
      phone_dashed: DesignToken;
      phone_outgoing: DesignToken;
      photo: DesignToken;
      photo_dashed: DesignToken;
      printer: DesignToken;
      rss: DesignToken;
      score: DesignToken;
      screen: DesignToken;
      server: DesignToken;
      smartphone: DesignToken;
      smart_contract: DesignToken;
      streaming: DesignToken;
      tablet: DesignToken;
      terminal: DesignToken;
      translate: DesignToken;
      ultra_cloud: DesignToken;
      usb: DesignToken;
      video: DesignToken;
      widgets: DesignToken;
      widgets_add: DesignToken;
      wifi: DesignToken;
      wifi_dashed: DesignToken;
      application: DesignToken;
      apps_grid: DesignToken;
      close: DesignToken;
      external_link: DesignToken;
      layers: DesignToken;
      log_in: DesignToken;
      log_out: DesignToken;
      menu: DesignToken;
      search: DesignToken;
      sidebar: DesignToken;
      windows_maximize: DesignToken;
      window_minimize: DesignToken;
      window_normalize: DesignToken;
      zoom_in: DesignToken;
      zoom_out: DesignToken;
      equal: DesignToken;
      equal_circle: DesignToken;
      hash: DesignToken;
      inequal: DesignToken;
      infinite: DesignToken;
      minus: DesignToken;
      minus_circle: DesignToken;
      percent: DesignToken;
      plus: DesignToken;
      plus_circle: DesignToken;
      x_circle: DesignToken;
      australian_dollar: DesignToken;
      bitcoin: DesignToken;
      brazilian_real: DesignToken;
      canadian_dollar: DesignToken;
      dollar: DesignToken;
      ether: DesignToken;
      euro: DesignToken;
      indian_rupee: DesignToken;
      korean_won: DesignToken;
      krona: DesignToken;
      mexican_peso: DesignToken;
      new_zealand_dollar: DesignToken;
      pound_sterling: DesignToken;
      swedish_krona: DesignToken;
      swiss_franc: DesignToken;
      uos: DesignToken;
      yen: DesignToken;
      yuan: DesignToken;
      currency_exchange: DesignToken;
      currency_receive: DesignToken;
      currency_send: DesignToken;
      dollar_to_uos: DesignToken;
      marketplace_auction: DesignToken;
      marketplace_cancel: DesignToken;
      marketplace_fixed: DesignToken;
      marketplace_inverted_auction: DesignToken;
      nft: DesignToken;
      nft_check: DesignToken;
      receive_nft: DesignToken;
      refund: DesignToken;
      refund_hand: DesignToken;
      resell: DesignToken;
      resell_cancel: DesignToken;
      resell_dashed: DesignToken;
      send_nft: DesignToken;
      trade: DesignToken;
      trade_dashed: DesignToken;
      uos_add: DesignToken;
      uos_receive: DesignToken;
      uos_to_dollar: DesignToken;
      uos_transfer: DesignToken;
      anchors: DesignToken;
      archive: DesignToken;
      auction_hammer: DesignToken;
      award: DesignToken;
      award_dashed: DesignToken;
      balance: DesignToken;
      bell_dashed: DesignToken;
      bell_on: DesignToken;
      book: DesignToken;
      bookmark: DesignToken;
      box: DesignToken;
      box_closed: DesignToken;
      box_open: DesignToken;
      cards: DesignToken;
      chess: DesignToken;
      chest: DesignToken;
      company: DesignToken;
      company_add: DesignToken;
      company_ban: DesignToken;
      company_freeze: DesignToken;
      crown: DesignToken;
      diamond: DesignToken;
      dice: DesignToken;
      explosion: DesignToken;
      factory: DesignToken;
      feather: DesignToken;
      fiole: DesignToken;
      flag: DesignToken;
      forge: DesignToken;
      gamepad: DesignToken;
      gamepad_oldschool: DesignToken;
      gamepad_dashed: DesignToken;
      gem: DesignToken;
      gift: DesignToken;
      glove: DesignToken;
      gun_pointer: DesignToken;
      helmet: DesignToken;
      home: DesignToken;
      inbox: DesignToken;
      key: DesignToken;
      lightbulb: DesignToken;
      lock_close: DesignToken;
      lock_open: DesignToken;
      megaphone: DesignToken;
      painting_palette: DesignToken;
      podium: DesignToken;
      puzzle: DesignToken;
      repair: DesignToken;
      rocket: DesignToken;
      shield: DesignToken;
      shield_dashed: DesignToken;
      plaintext: DesignToken;
      skull: DesignToken;
      sport: DesignToken;
      sword: DesignToken;
      swords: DesignToken;
      sword_shield: DesignToken;
      tag: DesignToken;
      ticket: DesignToken;
      trophy: DesignToken;
      vr: DesignToken;
      cast: DesignToken;
      copyright: DesignToken;
      fast_forward: DesignToken;
      image: DesignToken;
      image_add: DesignToken;
      image_dashed: DesignToken;
      image_landscape: DesignToken;
      image_portrait: DesignToken;
      live: DesignToken;
      maximize: DesignToken;
      minimize: DesignToken;
      music: DesignToken;
      pause: DesignToken;
      play: DesignToken;
      play_dashed: DesignToken;
      power: DesignToken;
      rewind: DesignToken;
      screen_share: DesignToken;
      skip_back: DesignToken;
      skip_forward: DesignToken;
      volume_0: DesignToken;
      volume_1: DesignToken;
      volume_2: DesignToken;
      volume_x: DesignToken;
      alert: DesignToken;
      asterisk: DesignToken;
      block: DesignToken;
      certified: DesignToken;
      check: DesignToken;
      check_circle: DesignToken;
      check_double: DesignToken;
      cross: DesignToken;
      cross_circle: DesignToken;
      dix_huit_plus: DesignToken;
      info: DesignToken;
      admin: DesignToken;
      user: DesignToken;
      user_add: DesignToken;
      user_check: DesignToken;
      user_group: DesignToken;
      user_group_add: DesignToken;
      user_group_check: DesignToken;
      user_group_remove: DesignToken;
      user_profile: DesignToken;
      user_remove: DesignToken;
      user_swap: DesignToken;
      user_team: DesignToken;
      calendar: DesignToken;
      calendar_dashed: DesignToken;
      clock: DesignToken;
      clock_dashed: DesignToken;
      history: DesignToken;
      hourglass: DesignToken;
      align_center: DesignToken;
      align_justify: DesignToken;
      align_left: DesignToken;
      align_right: DesignToken;
      bold: DesignToken;
      delete: DesignToken;
      emoji: DesignToken;
      italic: DesignToken;
      list_bullets: DesignToken;
      list_number: DesignToken;
      paragraph: DesignToken;
      type: DesignToken;
      type_1: DesignToken;
      type_2: DesignToken;
      type_3: DesignToken;
      underline: DesignToken;
      attachment: DesignToken;
      center_to_fit: DesignToken;
      copy: DesignToken;
      crop: DesignToken;
      download: DesignToken;
      drag: DesignToken;
      edit: DesignToken;
      eye_dashed: DesignToken;
      eye_on: DesignToken;
      filter: DesignToken;
      heart: DesignToken;
      heart_fill: DesignToken;
      link_alt: DesignToken;
      link_unlink: DesignToken;
      more_options: DesignToken;
      save: DesignToken;
      settings: DesignToken;
      share: DesignToken;
      sliders: DesignToken;
      sort: DesignToken;
      star: DesignToken;
      star_filled: DesignToken;
      thumbs_down: DesignToken;
      thumbs_up: DesignToken;
      trash: DesignToken;
      uninstall: DesignToken;
      upload: DesignToken;
      view_grid: DesignToken;
      view_list: DesignToken;
      wishlist_remove: DesignToken;
      arrow_corner_down_left: DesignToken;
      arrow_corner_down_right: DesignToken;
      arrow_corner_left_down: DesignToken;
      arrow_corner_left_up: DesignToken;
      arrow_corner_right_down: DesignToken;
      arrow_corner_right_up: DesignToken;
      arrow_corner_up_left: DesignToken;
      arrow_corner_up_right: DesignToken;
      arrow_down: DesignToken;
      arrow_down_left: DesignToken;
      arrow_down_right: DesignToken;
      arrow_left: DesignToken;
      arrow_right: DesignToken;
      arrow_up: DesignToken;
      arrow_up_left: DesignToken;
      arrow_up_right: DesignToken;
      chevron_down: DesignToken;
      chevron_left: DesignToken;
      chevron_right: DesignToken;
      chevron_up: DesignToken;
      collapse: DesignToken;
      collapse_horizontal: DesignToken;
      crossing_arrows: DesignToken;
      exchange_horizontal: DesignToken;
      exchange_vertical: DesignToken;
      expand: DesignToken;
      expand_horizontal: DesignToken;
      move: DesignToken;
      receive: DesignToken;
      refresh_ccw: DesignToken;
      refresh_cw: DesignToken;
      repeat: DesignToken;
      rotate_ccw: DesignToken;
      rotate_cw: DesignToken;
      send: DesignToken;
      shuffle: DesignToken;
      clipboard: DesignToken;
      clipboard_text: DesignToken;
      file: DesignToken;
      file_encrypted: DesignToken;
      file_text: DesignToken;
      file_text_double: DesignToken;
      folder: DesignToken;
      arena: DesignToken;
      ultra_prime: DesignToken;
      ultra_wallet: DesignToken;
      ultra_marketplace: DesignToken;
      first_hand_new_uniq: DesignToken;
      second_hand_uniq: DesignToken;
      ultra_games: DesignToken;
      ultra_logo: DesignToken;
      league: DesignToken;
      double_elim: DesignToken;
      gauntlet: DesignToken;
      round_robin: DesignToken;
      simple_stage: DesignToken;
      single_elim: DesignToken;
      swiss_system: DesignToken;
      bracket_group: DesignToken;
      uniq_unit: DesignToken;
      crypto_uos: DesignToken;
      screen_wide: DesignToken;
      workshop: DesignToken;
      cpu: DesignToken;
      arena_logo: DesignToken;
      ultra_prime_logo: DesignToken;
      ultra_wallet_logo: DesignToken;
      ultra_marketplace_logo: DesignToken;
      ultra_games_logo: DesignToken;
      no_result: DesignToken;
      library: DesignToken;
      minus_small: DesignToken;
      x: DesignToken;
      twitch: DesignToken;
      instagram: DesignToken;
      resell_lock: DesignToken;
      lock_exclusive_locked: DesignToken;
      lock_exclusive_open: DesignToken;
    };
  };
};
